// Code generated by ogen, DO NOT EDIT.
package fanbox

type CreatePostRes interface {
	createPostRes()
}

type DeletePostRes interface {
	deletePostRes()
}

type GetEditablePostRes interface {
	getEditablePostRes()
}

type ListManagedPostsRes interface {
	listManagedPostsRes()
}

type UpdatePostRes interface {
	updatePostRes()
}
