// Code generated by ogen, DO NOT EDIT.

package fanbox

// CreatePostParams is parameters of createPost operation.
type CreatePostParams struct {
	Origin string
}

// DeletePostParams is parameters of deletePost operation.
type DeletePostParams struct {
	Origin string
}

// GetEditablePostParams is parameters of getEditablePost operation.
type GetEditablePostParams struct {
	Origin string
	// Post's id.
	PostId string
}

// ListManagedPostsParams is parameters of listManagedPosts operation.
type ListManagedPostsParams struct {
	Origin string
}

// UpdatePostParams is parameters of updatePost operation.
type UpdatePostParams struct {
	Origin string
}
