name: Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'defaultcf/fanbox-specification tag'
        required: true
        type: string

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      
      - name: Download specification
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/defaultcf/fanbox-specification/releases/tags/${{ inputs.tag }}" \
            | jq ".assets[0].url" \
            | xargs -n1 curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/octet-stream" -L \
            > openapi.yaml

      - name: Generate
        run: |
          go generate ./...
          git config --local user.name  "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: generate"
          git push origin main
      - name: Versioning
        run: |
          git tag "${{ inputs.tag }}"
          git push origin "${{ inputs.tag }}"

  release:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
